version: '2'
services:

  # 公共镜像，只配置了国内镜像加速和中国时区配置
  alpine:
    build: alpine
    image: water/alpine

  mysql:
    build: mysql
    image: water/mysql
    depends_on:
      - "alpine"
    volumes:
      - "./volumes/mysql:/apps/mysql"
    ports:
      - "3306:3306"
    environment:
      # 默认的root密码和需要新建的数据库、用户名、密码，若需要重新设置，需要删除volumes/mysql/下面的全部内容，然后重新build
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vokuro
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    restart: always

  redis:
    build: redis
    image: water/redis
    depends_on:
      - "alpine"
    ports:
      - "6379:6379"
    restart: always

  nsqlookupd:
    image: natuka/nsq
    command: nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: natuka/nsq
    command: nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=127.0.0.1
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: natuka/nsq
    command: nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"

  phpfpm:
    build: phpfpm
    image: water/phpfpm
    depends_on:
      - "alpine"
    links:
      - mysql
      - redis
    volumes:
      - "./volumes/apps:/apps"
      # - "/Users/naive/app/miracle-top/server-api:/apps/server-api"
      - "/Users/naive/app/miracle-top/admin-api:/apps/server-api"
    restart: always

  nginx:
    build: nginx
    image: water/nginx
    depends_on:
      - "alpine"
    links:
      - phpfpm:phpfpm
    volumes_from:
      - phpfpm
    ports:
      - "80:80"
    restart: always